logging:
  file: # 日志输出到日志文件
    enable: true
    level: INFO
    path: logs # 路径
    rotation: "10 MB" # 日志文件截断大小
    retention: "7 days" # 日志保留时长
  console: # 日志输出到控制台
    enable: true
    level: INFO

db_meta:
  host: localhost
  port: 3306
  user: root
  password: 050710xxx
  database: meta

db_dw:
  host: localhost
  port: 3306
  user: root
  password: 050710xxx
  database: dw

qdrant:
  host: localhost
  port: 6333
  embedding_size: 1024

embedding:
  host: localhost
  port: 8081
  model: BAAI/bge-large-zh-v1.5


es:
  host: localhost
  port: 9200
  index_name: data_agent


llm:
  model_name: gpt-5.2-codex
  api_key: <api-key>
  base_url: https://api.openai-proxy.org/v1
